server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    # model.chat: openai
    openai:
      api-key: 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
      # base-url: https://openrouter.ai/api
      chat:
        options:
          model: gpt-4.1
          temperature: 0.0
      # embedding:
      #   options:
      #     model: qwen/qwen3-embedding-8b
